name       : libkdegames
version    : 23.04.0
release    : 70
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/libkdegames-23.04.0.tar.xz : 26c3afffd24b1efe41ebb839daba7ecbd7feceb290281e5b9ea5195a80bf55f2
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
#optimize   : lto
builddeps  :
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
