name       : libkdegames
version    : 22.12.1
release    : 69
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/libkdegames-22.12.1.tar.xz : 95351acdf3624a5913ab18d4c3e4acdd3c559b7df63e2541299088bcbf71fe29
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
#optimize   : lto
builddeps  :
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
