name       : libkdegames
version    : 18.12.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.12.0/src/libkdegames-18.12.0.tar.xz : 7b414075f135b93e1e332bbadf207f81c96c78d448b1f254d6015fc988052006
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
optimize   : lto
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
builddeps  :
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
rundeps    :
    - devel :
        - qt5-declarative-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
