name       : libkdegames
version    : 18.04.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/libkdegames-18.04.0.tar.xz : e6b628b80b6796ce50c8e17e7ea5e932f4e50a8d0552cf6c08104225da6e9d27
license    :
    - GFDL-1.2
    - GPL-2.0
component  : programming
optimize   : lto
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
