name       : libkdegames
version    : 22.04.2
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/libkdegames-22.04.2.tar.xz : c33af6c13540add132122b36b2faabc1f0beaf2c06d29e575f7789f1c5342911
homepage   : https://kde.org/
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
#optimize   : lto
builddeps  :
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Svg)
    - karchive-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kio-devel
    - knewstuff-devel
    - ktextwidgets-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
