name       : libkdegames
version    : 17.12.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.0/src/libkdegames-17.12.0.tar.xz : b3ff2fc4fb03029ced7783716c90645fc9d7a753eb8ace74081a6bfeece53150
license    :
    - GFDL-1.2
    - GPL-2.0
component  : programming
optimize   : lto
summary    : General purpose games code for KDE
description: |
    It is a collection of functions used by some games or which are useful for other games.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(sndfile)
    - pkgconfig(openal)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - extra-cmake-modules
    - karchive-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdnssd-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knewstuff-devel
    - kservice-devel
    - ktextwidgets-devel
    - kwidgetsaddons-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
